# Generated by Django 4.0.4 on 2022-04-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=25, verbose_name='할일')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료여부')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='기한')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='유저')),
            ],
            options={
                'verbose_name_plural': '할일',
            },
        ),
    ]
