# Generated by Django 4.0.4 on 2022-05-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('todo', models.CharField(max_length=25, verbose_name='할일')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료여부')),
            ],
            options={
                'verbose_name_plural': '할일',
            },
        ),
    ]
