# Generated by Django 4.0.4 on 2022-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat_cycle',
            field=models.IntegerField(choices=[(0, '없음'), (1, '월'), (2, '화'), (3, '수'), (4, '목'), (5, '금'), (6, '토'), (7, '일')], default=0, verbose_name='반복주기'),
        ),
    ]
