# Generated by Django 4.0.4 on 2022-04-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_todo_created_todo_repeat_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
