# Generated by Django 4.0.4 on 2022-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='아이디')),
                ('password', models.CharField(max_length=12, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=8, verbose_name='닉네임')),
            ],
            options={
                'verbose_name_plural': '유저',
            },
        ),
    ]
